OrchidEDIWeb/Pages/ManageClaims/ClaimHistory.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OrchidEDIWeb.Pages.ManageClaims
{
    [Authorize]
    public class ClaimHistoryModel : PageModel
    {
        public void OnGet()
        {
        }
        public void OnPostSearch()
        {
            string searchBy = Request.Form["ddlSearchBy"];            
            string filterName = Request.Form["txtFilterName"];

            string filterToggleAccountNo = Request.Form["btnFilterAcctNoToggle"];
            string filterAcctNoStart = Request.Form["txtFilterAcctNoFrom"];
            string filterAcctNoTo = Request.Form["txtFilterAcctNoTo"];

            string filterToggleDOS = Request.Form["btnFilterDOSToggle"];
            string filterDOSStart = Request.Form["dateDosStart"];
            string filterDOSEnd = Request.Form["dateDosStart"];

            string filterToggleSubmitDate = Request.Form["btnFilterSubmitDateToggle"];
            string filterSubmitStart = Request.Form["dateSubmitStart"];
            string filterSubmitEnd = Request.Form["dateSubmitEnd"];
            
            //Search
        }
    }
}

OrchidEDIWeb/Pages/ManageClaims/ReceiveFile.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OrchidEDIWeb.Pages.ManageClaims
{
    public class ReceiveFileModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

OrchidEDIWeb/Pages/ManageClaims/SendFile.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using OrchidEDIWeb.Data;
using Serilog;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace OrchidEDIWeb.Pages.ManageClaims
{
    [Authorize]
    public class SendFileModel : PageModel
    {
        private IHostingEnvironment _environment;
        private readonly DatabaseContext _ctx;
        private readonly IConfiguration _config;

        public SendFileModel(IHostingEnvironment environment, DatabaseContext ctx, IConfiguration config)
        {
            _environment = environment;
            _ctx = ctx;
            _config = config;
        }
        [BindProperty]
        public IFormFile Upload { get; set; }
        public IEnumerable<Data.tblFile> Files { get; set; }
        public IEnumerable<string> Pages { get; set; }
        public async Task OnPostUploadFileAsync()
        {
            try
            {
                string fileName = Path.GetFileName(Upload.FileName);
                //Cannot have duplicate file name in the same day
                var vExistingFile = _ctx.tblFile.Where(t => t.FileName == fileName && 
                        t.ReceivedDate >= DateTime.Now.Date && t.ReceivedDate< DateTime.Now.AddDays(1).Date)
                        .Select(t => new {
                            t.FileID
                        }).ToList();
                if (vExistingFile.Count > 0)
                    TempData["error"] = "File already uploaded.";
                else
                {
                    //Path for keep Upload Files: UploadFiles\[clientID]\[uploadDate(yyyyddMM)]\
                    string todayDate = DateTime.Now.ToString("yyyyddMM");
                    int clientID = int.Parse(((ClaimsIdentity)User.Identity).FindFirst("ClientID").Value);
                    string wwwPath = _environment.WebRootPath;
                    string contentPath = _environment.ContentRootPath;
                    string path = Path.Combine(wwwPath, "UploadFiles");
                    if (!Directory.Exists(path))
                        Directory.CreateDirectory(path);
                    path = Path.Combine(path, todayDate);
                    if (!Directory.Exists(path))
                        Directory.CreateDirectory(path);
                    path = Path.Combine(path, clientID.ToString());
                    if (!Directory.Exists(path))
                        Directory.CreateDirectory(path);

                    var file = Path.Combine(path, Upload.FileName);
                    using (var fileStream = new FileStream(file, FileMode.Create))
                    {
                        await Upload.CopyToAsync(fileStream); //This one will replace the existing file.
                    }

                    _ctx.Database.ExecuteSqlRaw("Insert into tblFile ([ClientID],[FileName],[ReceivedDate],[FileStatusID]) Values({0},{1},{2},{3})", clientID,fileName, DateTime.Now, 1);
                    
                    TempData["success"] = fileName + " was received successfully.";
                }
                HttpContext.Session.SetInt32("PageNumber", 1);
                GetFiles();
            }
            catch(Exception ex)
            {
                TempData["error"] = "Error has accured. Please contact administrator.";
                Log.Error("Login Error: " + ex.Message);
            }
        }
        public Task OnGet()
        {
            HttpContext.Session.SetInt32("PageNumber", 1);
            GetFiles();
            return Task.CompletedTask;
        }

        public void OnPostPageNavigate(string nav)
        {
            int totalPages = (int)HttpContext.Session.GetInt32("TotalPages");
            int currentPageNumber = (int)HttpContext.Session.GetInt32("PageNumber");
            int nextPageNumber = 1;
            switch (nav)
            {
                case "first":
                    HttpContext.Session.SetInt32("PageNumber", 1);
                    break;
                case "prev":
                    nextPageNumber = (currentPageNumber > 1) ? currentPageNumber - 1 : 1;
                    HttpContext.Session.SetInt32("PageNumber", nextPageNumber);
                    break;
                case "next":
                    nextPageNumber = (currentPageNumber < totalPages) ? currentPageNumber + 1 : totalPages;
                    HttpContext.Session.SetInt32("PageNumber", nextPageNumber);
                    break;
                case "last":
                    HttpContext.Session.SetInt32("PageNumber", totalPages);
                    break;
            }
            GetFiles();
            //TempData["error"] = $"{nav}";
        }
        private void GetFiles()
        {
            ViewData["PageNo"] = HttpContext.Session.GetInt32("PageNumber").ToString();
            SqlParameter[] sqlParameters = new SqlParameter[7];
            sqlParameters[0] = new SqlParameter("@searchBy", System.Data.SqlDbType.VarChar);
            sqlParameters[0].Value = "FileName";
            sqlParameters[1] = new SqlParameter("@keyword", System.Data.SqlDbType.VarChar);
            sqlParameters[1].Value = "";
            sqlParameters[2] = new SqlParameter("@sortBy", System.Data.SqlDbType.VarChar);
            sqlParameters[2].Value = "TF.ReceivedDate";
            sqlParameters[3] = new SqlParameter("@viewOrder", System.Data.SqlDbType.Bit);
            sqlParameters[3].Value = 1;
            sqlParameters[4] = new SqlParameter("@pageSize", System.Data.SqlDbType.Int);
            sqlParameters[4].Value = _config.GetValue<int>("PageSize");
            sqlParameters[5] = new SqlParameter("@pageNumber", System.Data.SqlDbType.Int);
            sqlParameters[5].Value = HttpContext.Session.GetInt32("PageNumber");
            sqlParameters[6] = new SqlParameter("@totalPage", System.Data.SqlDbType.Int);
            sqlParameters[6].Direction = System.Data.ParameterDirection.Output;

            Files = _ctx.tblFile.FromSqlRaw($"EXEC [dbo].[tblFileSelectAllFilter] @searchBy, @keyword, @sortBy, @viewOrder, @pageSize, @pageNumber, @totalPage OUTPUT",
                sqlParameters).ToList();

            int totalPage = (int)sqlParameters[6].Value;
            HttpContext.Session.SetInt32("TotalPages", totalPage);
            //Pages = new IEnumerable<string>();
            List<string> strPages = new List<string>();
            for (int i = 1; i <= totalPage; i++)
                strPages.Add(i.ToString());

            Pages = strPages.ToList();
        }
    }
}

OrchidEDIWeb/Pages/ManageClaims/ClaimHistory.cshtml
@page "ClaimHistory"
@model OrchidEDIWeb.Pages.ManageClaims.ClaimHistoryModel
@{
}
<div class="mt-20">
    <partial name="_ManageClaimsNav" />
</div>
<div>
    <div class="mt-2">
        <partial name="_Message" />
    </div>
    <div class="text-primary">Search Claim History</div>
    <form method="post">
        <table cellpadding="3">
            <tr>
                <td width="140px"><label>Search By</label></td>
                <td colspan="2">
                    <select id="ddlSearchBy" name="ddlSearchBy" class="form-select" aria-label="Search By">
                        <option value="patient" style="line-height:30px;">Patient</option>
                        <option value="provider" style="line-height:30px;">Provider</option>
                        <option value="payer" style="line-height:30px;">Payer</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td><label>Account #</label></td>
                <td width="80px"><button id="btnFilterAcctNo" name="btnFilterAcctNo" type="button" class="badge bg-light" style="width:80px;" onclick="OnbtnFilterToggle('btnFilterAcctNo');">[ALL]</button></td>
                <td width="50px">From</td>
                <td><input type="text" class="form-control" id="txtFilterAcctNoFrom" name="txtFilterAcctNoFrom" style="width:150px;"></td>
                <td width="40px" align="center">To</td>
                <td><input type="text" class="form-control" id="txtFilterAcctNoTo" name="txtFilterAcctNoTo" style="width:150px;"></td>
                <td> <input type="hidden" id="btnFilterAcctNoToggle" name="btnFilterAcctNoToggle" value="all"></td>
            </tr>
            <tr>
                <td><label>Name</label></td>
                    <td colspan="4"><input type="text" class="form-control" id="txtFilterName" name="txtFilterName" style="width:290px;"></>
            </tr>
            <tr>
                <td><label>Date of Service</label></td>
                <td><button id="btnFilterDOS" name="btnFilterDOS" type="button" class="badge bg-light" style="width:80px;" onclick="OnbtnFilterToggle('btnFilterDOS');">[ALL]</button></td>
                <td>From</td>
                <td>
                    <input name="dateDosStart" id="dateDosStart" type="date" class="form-control" value="" />
                </td>
                <td width="40px" align="center">To</td>
                <td><input name="dateDosEnd" id="dateDosEnd" type="date" class="form-control" value="" /></td>
                <td> <input type="hidden" id="btnFilterDOSToggle" name="btnFilterDOSToggle" value="all"></td>
            </tr>
            <tr>
                <td><label>Submission Date</label></td>
                <td><button id="btnFilterSubmitDate" name="btnFilterSubmitDate" type="button" class="badge bg-light" style="width:80px;" onclick="OnbtnFilterToggle('btnFilterSubmitDate');">[ALL]</button></td>
                <td>From</td>
                <td><input name="dateSubmitStart" id="dateSubmitStart" type="date" class="form-control" /></td>
                <td width="40px" align="center">To</td>
                <td><input name="dateSubmitEnd" id="dateSubmitEnd" type="date" class="form-control"/></td>
                <td> <input type="hidden" id="btnFilterSubmitDateToggle" name="btnFilterSubmitDateToggle" value="all"></td>
            </tr>
            <tr>
                <td><button id="btnSearch" type="submit" class="btn btn-primary" href="" asp-page-handler="Search">Search</button></td>
        </tr>
        </table>
    </form>    
    <div class="mt-3">
        <div class="text-primary">List Claim</div>
        <div class="table-fix-header">
            <table id="listTable" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>File Name</th>
                        <th>Submit Date</th>
                        <th>DOS</th>
                        <th>Patient Name</th>
                        <th>Provider Name</th>
                        <th>Payer</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    @* @if (Model.Files != null)
                    {
                        @foreach (var file in Model.Files)
                        {
                            <tr>
                                <td>@file.FileName</td>
                                <td>@file.ReceivedDate</td>
                                <td>@file.FileStatusName</td>
                            </tr>
                        }
                    }
                    else
                    { *@
                        <tr><td colspan="7">No Data</td></tr>
                    @* } *@
                </tbody>
            </table>
        </div>
    </div>
    <div class="mt-2">
        <form method="post">
            <input name="navFirst" asp-page-handler="PageNavigate" asp-route-nav="first" type="submit" value=&#9198; style='background-color:transparent; border:none;font-size:30px;' />
            <input name="navPrev" asp-page-handler="PageNavigate" asp-route-nav="prev" type="submit" value=&#9204; style='background-color:transparent; border:none;font-size:30px;' />
            <label style='font-size:20px;' for="page">Page:</label>
            <select style='font-size:20px;' name="pages" id="pages">
                @* @if (Model.Pages != null)
                {
                    @foreach (var pageIdx in Model.Pages)
                    {
                        @if (ViewData["PageNo"] == pageIdx)
                        {
                            <option value=@pageIdx selected> @pageIdx </option>
                        }
                        else
                        {
                            <option value=@pageIdx> @pageIdx </option>
                        }
                    }
                } *@
            </select>

            <input name="navNext" asp-page-handler="PageNavigate" asp-route-nav="next" type="submit" value=&#9205; style='background-color:transparent; border:none;font-size:30px;' />
            <input name="navLast" asp-page-handler="PageNavigate" asp-route-nav="last" type="submit" value=&#9197; style='background-color:transparent; border:none;font-size:30px;' />

        </form>
    </div>
</div>

<script type="text/javascript">
    function OnbtnFilterToggle(btnFilterName) {
        if (document.getElementById(btnFilterName).innerText == "[ALL]")
            document.getElementById(btnFilterName).innerText = "[RANGE]";
        else
            document.getElementById(btnFilterName).innerText = "[ALL]";

        document.getElementById(btnFilterName + 'Toggle').value = document.getElementById(btnFilterName).innerText;
        alert(document.getElementById(btnFilterName + 'Toggle').value);
    }
</script>

OrchidEDIWeb/Pages/ManageClaims/ReceiveFile.cshtml
@page "/ReceiveFile"
@model OrchidEDIWeb.Pages.ManageClaims.ReceiveFileModel
@{
}
<div class="mt-2">
<partial name="_ManageClaimsNav" />
<h1>Receive File - Get the response files or result</h1>
</div>

OrchidEDIWeb/Pages/ManageClaims/SendFile.cshtml
@page "/SendFile"

@model OrchidEDIWeb.Pages.ManageClaims.SendFileModel
@{
    
}


<div class="mt-20">
    <partial name="_ManageClaimsNav" />
</div>
<div>
    <div class="mt-2">
        <partial name="_Message" />
    </div>
    <div class="mt-2">
        <form method="post" enctype="multipart/form-data">
            <div class="text-primary">Send Claims</div>
            <div>Select ansi file to upload
                <input type="file" asp-for="Upload" />
                <input asp-page-handler="UploadFile" type="submit" />
            </div>
            @* <div>
                <span>@Html.Raw(Model.Message)</span>
            </div> *@
        </form>
    </div> 
    <div class="mt-3">
        <div class="text-primary">List Received Files</div>
            <div class="table-fix-header">
                <table id="listTable" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>File Name</th>
                            <th>Received Date</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    @if (Model.Files != null)
                    {
                        @foreach (var file in Model.Files)
                        {
                            <tr>
                                <td>@file.FileName</td>
                                <td>@file.ReceivedDate</td>
                                <td>@file.FileStatusName</td>
                            </tr>
                        }
                    } else
                    {
                        <tr><td colspan="3">No Data</td></tr>
                    }
                </tbody>
                </table>
            </div>
    </div>      
    <div class="mt-2">
        <form method="post">
            <input name="navFirst" id="navFirst" asp-page-handler="PageNavigate" asp-route-nav="first" type="submit" value=&#9198; style='background-color:transparent; border:none;font-size:30px;' />
            <input name="navPrev" asp-page-handler="PageNavigate" asp-route-nav="prev" type="submit" value=&#9204; style='background-color:transparent; border:none;font-size:30px;' />
            <label style='font-size:20px;' for="page">Page:</label>
            <select style='font-size:20px;' name="pages" id="pages">
                @if (Model.Pages != null)
                {
                    @foreach (var pageIdx in Model.Pages)
                    {
                        @if (ViewData["PageNo"] == pageIdx) {
                            <option value=@pageIdx selected> @pageIdx </option>
                        } else { 
                            <option value=@pageIdx> @pageIdx </option>
                        }
                    }
                }
            </select>

            <input name="navNext" asp-page-handler="PageNavigate" asp-route-nav="next" type="submit" value=&#9205; style='background-color:transparent; border:none;font-size:30px;' />
            <input name="navLast" asp-page-handler="PageNavigate" asp-route-nav="last" type="submit" value=&#9197; style='background-color:transparent; border:none;font-size:30px;' />

        </form>
    </div>
</div>
<script type="text/javascript">
    $('#listTable tbody tr').click(function () {        
        $(this).addClass('table-warning').siblings().removeClass('table-warning');
    });
</script>

               