OrchidEDIWeb/Pages/User/Create.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OrchidEDIWeb.Data;
using System.Security.Claims;

namespace OrchidEDIWeb.Pages.User
{
    [Authorize]
    //[Authorize(Policy = "Admin")]  // <-- "Admin" (Role)
    public class CreateModel : PageModel
    {
        private readonly DatabaseContext _ctx;

        public CreateModel(DatabaseContext ctx)
        {
            _ctx = ctx;
        }
        [BindProperty]
        public Data.TblUser TblUser { get; set; }
        [BindProperty]
        public Data.tbxUserClient UserClient { get; set; }
        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if(!ModelState.IsValid)
                return Page();

            var transaction = _ctx.Database.BeginTransaction();
            try
            {
                if(TblUser == null || UserClient == null)
                    return NotFound();
                _ctx.TblUser.Add(TblUser);
                _ctx.SaveChanges();

                UserClient.ClientId = int.Parse(((ClaimsIdentity)User.Identity).FindFirst("ClientID").Value);
                UserClient.UserId = TblUser.Id;
                _ctx.tbxUserClient.Add(UserClient);
                _ctx.SaveChanges();

                transaction.Commit();

                TempData["success"] = "Saved successfully";
                return RedirectToPage("DisplayAll");
            }
            catch (Exception ex)
            {
                TempData["error"] = "Error has accured";
                return Page();
            }
            //return RedirectToPage(); //This is for back to page with emtpy fields
        }
    }
}

OrchidEDIWeb/Pages/User/DisplayAll.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using OrchidEDIWeb.Data;
using System.Data;
using System.Security.Claims;

namespace OrchidEDIWeb.Pages.User
{
    [Authorize]
    //[Authorize(Policy = "UserPolicy")]
    //[Authorize(Roles = "Admin")]
    public class DisplayAllModel : PageModel
    {
        private readonly DatabaseContext _ctx;

        public DisplayAllModel(DatabaseContext ctx)
        {
            _ctx = ctx;
        }
        public List<Data.TblUserEx> Users { get; set; }
        
        public IActionResult OnGet()
        {
            ClaimsPrincipal principal = HttpContext.User as ClaimsPrincipal;
            if (null != principal)
            {
                foreach (Claim claim in principal.Claims)
                {
                    string str = ("CLAIM TYPE: " + claim.Type + "; CLAIM VALUE: " + claim.Value + "</br>");
                }
            }

            LoadUserList();
            //Users = _ctx.TblUser.Where(u => u.ClientID == clientID).ToList();
            return Page();
        }

        public Task<IActionResult> OnPostDeleteAsync(int userClientId, int id)
        {
            var user = _ctx.TblUser.Find(id);
            var userClient = _ctx.tbxUserClient.Find(userClientId);
            if(user == null || userClient == null)
                return Task.FromResult<IActionResult>(NotFound());

            var transaction = _ctx.Database.BeginTransaction();
            try
            {
                //Dont delete user data, because its related with other tables (createdBy, changedBy etc)
                //_ctx.TblUser.Remove(user);
                //_ctx.SaveChanges();
                
                _ctx.tbxUserClient.Remove(userClient);
                _ctx.SaveChanges();

                transaction.Commit();

                TempData["success"] = "Deleted Successfully";
            }
            catch (Exception ex)
            {
                TempData["error"] = "Error on deleteing record";                    
            }
            return Task.FromResult<IActionResult>(RedirectToPage());
        }

        private void LoadUserList()
        {
            SqlParameter[] sqlParams = new SqlParameter[1];
            sqlParams[0] = new SqlParameter("@ClientId", SqlDbType.VarChar);
            sqlParams[0].Value = int.Parse(((ClaimsIdentity)User.Identity).FindFirst("ClientID").Value);
            DataTable dtUsers = DbContextExtensions.ExecuteQuery(_ctx, "tblUserSelectAllByClient", sqlParams, "StoreProcedure");
            Users = new List<TblUserEx>();
            for(int i= 0; i < dtUsers.Rows.Count; i++)
            {
                TblUserEx user = new TblUserEx();
                user.Id = Convert.ToInt32(dtUsers.Rows[i]["id"]);
                user.LastName = dtUsers.Rows[i]["LastName"].ToString()!;
                user.FirstName = dtUsers.Rows[i]["FirstName"].ToString()!;
                user.UserName = dtUsers.Rows[i]["UserName"].ToString()!;
                user.Email = dtUsers.Rows[i]["Email"].ToString()!;
                user.IsActive = Convert.ToBoolean(dtUsers.Rows[i]["IsActive"]);
                user.UserClientId = Convert.ToInt32(dtUsers.Rows[i]["UserClientId"]);

                this.Users.Add(user);
            }
        }
    }
}

OrchidEDIWeb/Pages/User/Edit.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OrchidEDIWeb.Data;
using Serilog;
using System.Security.Claims;

namespace OrchidEDIWeb.Pages.User
{
    [Authorize]
    public class EditModel : PageModel
    {
        private readonly DatabaseContext _ctx;

        public EditModel(DatabaseContext ctx)
        {
            _ctx = ctx;
        }
        [BindProperty]
        public Data.TblUser TblUser { get; set; }
        [BindProperty]
        public Data.tbxUserClient UserClient { get; set; }
        public IActionResult OnGet(int id)
        {
            var user = (from x in _ctx.tbxUserClient 
                            join u in _ctx.TblUser on x.UserId equals u.Id 
                            join c in _ctx.tblClient on x.ClientId equals c.ClientID 
                            where x.UserId == id
                       select new { UserClientId = x.Id, ClientId = x.ClientId, Id = u.Id, LastName = u.LastName, FirstName = u.FirstName, UserName = u.UserName, Password = u.Password, Email = u.Email, IsActive = x.IsActive }).First();
            //var user = _ctx.TblUser.Find(id);
            if(user == null)
                return NotFound();
            TblUser = new TblUser();
            TblUser.Id = user.Id;
            TblUser.LastName = user.LastName;
            TblUser.FirstName = user.FirstName; 
            TblUser.UserName = user.UserName;
            TblUser.Password = user.Password;
            TblUser.Email = user.Email;

            UserClient = new tbxUserClient();
            UserClient.Id = user.UserClientId;
            UserClient.UserId = user.Id;
            UserClient.ClientId = user.ClientId;
            UserClient.IsActive = user.IsActive;
            
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
                return Page();

            var transaction = _ctx.Database.BeginTransaction();
            try
            {
                if (TblUser == null || UserClient == null)
                    return NotFound();

                _ctx.TblUser.Update(TblUser);
                _ctx.SaveChanges();

                _ctx.tbxUserClient.Update(UserClient);
                _ctx.SaveChanges();

                transaction.Commit();
                TempData["success"] = "Edit successfully";

                ////First get user claims, to get login information
                //var claims = ClaimsPrincipal.Current.Identities.First().Claims.ToList();

                ////Filter specific claim    
                //claims?.FirstOrDefault(x => x.Type.Equals("UserName", StringComparison.OrdinalIgnoreCase))?.Value
                //    .ToString();

                return RedirectToPage("DisplayAll");
            }
            catch (Exception ex)
            {
                TempData["error"] = "Error has accured. Please contact Administrator.";
                Log.Error("Edit User Error: " + ex.Message);
                return Page();
            }
        }
    }
}

OrchidEDIWeb/Pages/User/Create.cshtml
@page "/User/New"
@model OrchidEDIWeb.Pages.User.CreateModel
@{
}
<partial name="_Message" />

<div>
    <h1>Add New User</h1>
    <form asp-action="Create">
        <div class="form-group">
            <label asp-for="TblUser.LastName"></label>
            <input asp-for="TblUser.LastName" class="form-control" />
            <span class="text-danger" asp-validation-for="TblUser.LastName"></span>
        </div>
        <div class="form-group">
            <label asp-for="TblUser.FirstName"></label>
            <input asp-for="TblUser.FirstName" class="form-control" />
            <span class="text-danger" asp-validation-for="TblUser.FirstName"></span>
        </div>
        <div class="form-group">
            <label asp-for="TblUser.UserName"></label>
            <input asp-for="TblUser.UserName" class="form-control" />
            <span class="text-danger" asp-validation-for="TblUser.UserName"></span>
        </div>
        <div class="form-group">
            <label asp-for="TblUser.Password"></label>
            <input asp-for="TblUser.Password" class="form-control" type="password" />
            <span class="text-danger" asp-validation-for="TblUser.Password"></span>
        </div>
        <div class="form-group">
            <label asp-for="TblUser.Email"></label>
            <input asp-for="TblUser.Email" class="form-control" />
            <span class="text-danger" asp-validation-for="TblUser.Email"></span>
        </div>
        <div class="form-check">
            <label class="form-check-label" for="UserClient.IsActive"> Active</label>
            <input asp-for="UserClient.IsActive" class="form-check-input" type="checkbox" >
        </div>
        <div class="my-2">
            <button class="btn btn-primary">Save</button>
            <a asp-page="DisplayAll" class="btn btn-secondary">Show All Records</a>
        </div>
    </form>
</div>

OrchidEDIWeb/Pages/User/DisplayAll.cshtml
@page "/User/List"
@model OrchidEDIWeb.Pages.User.DisplayAllModel
@{
}
<partial name="_Message" />
<div>
    <div class="mb-2"> <a asp-page="Create" class="btn btn-primary">Add new user</a>
        @* <button class="btn btn-primary">Add new user</button>  *@
    </div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Username</th>
                <th>Email</th>
                <th>Active</th>
                <th colspan="2">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var user in Model.Users)
            {
                <tr>
                    <td>@(user.LastName +", " + user.FirstName)</td>
                    <td>@user.UserName</td>
                    <td>@user.Email</td>
                    <td><input asp-for=@user.IsActive class="form-check-input" type="checkbox" id="chkIsActive" name="chkIsActive" value="" onclick="return false;"></td>
                    <td>
                        <a asp-page="Edit" asp-route-id="@user.Id" class="btn btn-primary">Edit</a>
                    </td>
                    <td>
                        <form asp-page="DisplayAll">
                            <button onclick="return confirm('Are you sure?');" asp-page-handler="Delete" asp-route-userClientId="@user.UserClientId" asp-route-id="@user.Id" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>

OrchidEDIWeb/Pages/User/Edit.cshtml
@page "/User/Edit"
@model OrchidEDIWeb.Pages.User.EditModel
@{
}
<partial name="_Message" />

<div>
    <h1>Edit User</h1>
    <form asp-action="Edit">
        <input type="hidden" asp-for="TblUser.Id" class="form-control" />
        <input type="hidden" asp-for="UserClient.Id" class="form-control" />
        <input type="hidden" asp-for="UserClient.UserId" class="form-control" />
        <input type="hidden" asp-for="UserClient.ClientId" class="form-control" />

        <div class="form-group">
            <label asp-for="TblUser.LastName"></label>
            <input asp-for="TblUser.LastName" class="form-control" />
            <span class="text-danger" asp-validation-for="TblUser.LastName"></span>
        </div>
        <div class="form-group">
            <label asp-for="TblUser.FirstName"></label>
            <input asp-for="TblUser.FirstName" class="form-control" />
            <span class="text-danger" asp-validation-for="TblUser.FirstName"></span>
        </div>
        <div class="form-group">
            <label asp-for="TblUser.UserName"></label>
            <input asp-for="TblUser.UserName" class="form-control" />
            <span class="text-danger" asp-validation-for="TblUser.UserName"></span>
        </div>
        <div class="form-group">
            <label asp-for="TblUser.Password"></label>
            <input asp-for="TblUser.Password" class="form-control" type="password" />
            <span class="text-danger" asp-validation-for="TblUser.Password"></span>
        </div>
        <div class="form-group">
            <label asp-for="TblUser.Email"></label>
            <input asp-for="TblUser.Email" class="form-control" />
            <span class="text-danger" asp-validation-for="TblUser.Email"></span>
        </div>
        <div class="form-check">
            <label class="form-check-label" for="UserClient.IsActive"> Active</label>
            <input asp-for="UserClient.IsActive" class="form-check-input" type="checkbox" >
        </div>
        <div class="my-2">
            <button class="btn btn-primary">Update</button>
            <a asp-page="DisplayAll" class="btn btn-secondary">Show All Records</a>
        </div>
    </form>
</div>